### ISSUE TITLE
Race in blinky due to errata

### ISSUE THREAD

**Issue by tonyarkles** [rowol/stm32_discovery_arm_gcc#1]
Hi! Not sure if this is maintained or not, but last night I dug deep into an issue I was having: If I built blinky and flashed it to my discovery board, the LEDs wouldn't flash after a Reset, but they would if I connected with st-util/gdb and restarted it.

I dove deep into it and discovered that it was related to optimization, sort of. With -O2 (default in the Makefile) it wouldn't work, but with -O0 it would. It took a while, but I found this little gem in the Errata for the processor:

```
A delay between an RCC peripheral clock enable and the effective peripheral enabling
should be taken into account in order to manage the peripheral read/write to registers.
This delay depends on the peripheral’s mapping:
- If the peripheral is mapped on AHB: the delay should be equal to 2 AHB cycles.
```
With the default clock config, 2 AHB cycles = 4 sysclk cycles. With -O2, recent gcc was compiling down to assembler that would execute in 3 sysclk cycles and was violating the timing constraints found in the Errata. 

Adding a single NOP between the `RCC->AHB1ENR` and `GDIOD->MODER` lines was enough to fix it. The Errata sheet says that a DSB instruction is probably the right answer there.

In my googling last night to try to figure this out, I came across a number of threads where people were having the same issue, but none of them came to any resolution on it.

**Comment by rowol** [comment]
Sorry, I only just saw this notification now (over a year later)   =(   Someone had also posted this on a forum (maybe you also) and someone else reading the forum send me an email about it.  

If you take a look at the fix I submitted this May 2015, I did fix the problem by adding a DSB instruction which dumps the instruction pipeline... this is more reliable than adding the NOP, and is also mentioned in the errata.   
https://github.com/rowol/stm32_discovery_arm_gcc/commit/78c3ecceb0d404c8a686ea2b8e30840665989163

If you need to contact me again for something, you can email directly to rowol@mysticind.com

Thanks,
Ross

**Comment by tonyarkles** [comment]
No worries! I ended up using a DSB too. My project has come a long way from that post, but this really helped me get started! Thanks!

**Comment by rowol** [comment]
Thanks, I'm glad the tutorial was useful!
